trigger:
  - main

# schedules:
#   - cron: "30 3 * * 1-5"
#     displayName: Weekday Build Auto Trigger
#     branches:
#       include:
#         - main
#     always: true

pool:
  vmImage: ubuntu-latest

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "18"
    displayName: "Install Node.js"

  - script: npm ci
    displayName: "npm ci"

  #    workingDirectory: "$(Build.SourcesDirectory)/FolderNameInAny"

  - script: npx playwright install --with-deps
    displayName: "Install Playwright browsers"

  - script: npx playwright test --grep test
    displayName: "Run Playwright tests"
    env:
      CI: "true"

  - task: PublishTestResults@2
    displayName: "Publish test results"
    inputs:
      testResultsFormat: "JUnit"
      testResultsFiles: "junit-test-report.xml"
      mergeTestResults: true
      failTaskOnFailedTests: true
      testRunTitle: "My End-To-End Tests"
    condition: succeededOrFailed()

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: playwright-report
      artifact: playwright-report
      publishLocation: "pipeline"
    condition: succeededOrFailed()